CREATE TABLE IF NOT EXISTS `production_info` (
  `id` int(64) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(255) DEFAULT '' comment '作品编号',
  `name` VARCHAR(255) DEFAULT '' comment '作品标题',
  `author` VARCHAR(255) DEFAULT '' comment '作品作者',
  `sort` VARCHAR(255) DEFAULT '' comment '作品所属类别',
  `cover` VARCHAR(255) DEFAULT '' comment '作品上传',
  `describe` VARCHAR(255) DEFAULT '' comment '作品简述',
  `photography_props` VARCHAR(255) DEFAULT '' comment '摄影道具',
  `photography_site` VARCHAR(255) DEFAULT '' comment '摄影地点',
  `content` VARCHAR(255) DEFAULT '' comment '作品描述详情',
  `content_markdown` VARCHAR(255) DEFAULT '' comment '作品描述详情markdown格式',
  `create_time` bigint comment '作品发布时间',
  `update_time` bigint comment '作品信息编辑时间',
  `disabled` INT(2) DEFAULT 0 comment '是否屏蔽作品 - 0 正常 - 1 屏蔽',
  `status` INT(2) DEFAULT 0 comment '是否审核通过 - 0 通过 - 1 不通过',
  `auditor` VARCHAR(255) DEFAULT '' comment '审核通过管理员编号',
  `commentIds` VARCHAR(255) DEFAULT '' comment '评论的所有楼层id集合',
  `attentionIds` VARCHAR(255) DEFAULT '' comment '所有关注id集合',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
