CREATE TABLE IF NOT EXISTS `production_info` (
  `id` INT(64) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(255) DEFAULT '' comment '作品编号',
  `name` VARCHAR(255) DEFAULT '' comment '作品标题',
  `author_id` INT(64) comment '冗余作者id',
  `sort` VARCHAR(255) DEFAULT '' comment '作品所属类别',
  `activity_id` INT(64) comment '该作品参加的活动id',
  `production` LONGTEXT comment '作品上传',
  `banner` VARCHAR(255) DEFAULT '' comment 'banner上传',
  `cover` VARCHAR(255) DEFAULT '' comment '封面上传',
  `describe` LONGTEXT comment '作品简述',
  `photography_props` VARCHAR(255) DEFAULT '' comment '摄影道具',
  `photography_site` VARCHAR(255) DEFAULT '' comment '摄影地点',
  `content` LONGTEXT comment '作品描述详情',
  `content_markdown` VARCHAR(255) DEFAULT '' comment '作品描述详情markdown格式',
  `comment_number` INT(20) comment '评论数量',
  `view_number` INT(20) comment '浏览量',
  `create_time` bigint comment '作品发布时间',
  `update_time` bigint comment '作品信息编辑时间',
  `disabled` INT(2) DEFAULT 0 comment '是否屏蔽作品 - 0 正常 - 1 屏蔽',
  `status` INT(2) DEFAULT 0 comment '是否审核通过 - 0 通过 - 1 不通过',
  `is_delete` INT(2) DEFAULT 0 comment '是否删除 - 0 不删除 - 1 删除',
  `auditor` VARCHAR(255) DEFAULT '' comment '审核通过管理员编号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
